print("Hello World this is manish")
print("Changes")
print("learning commits and pusing the files")
print("relearning and practise")
print("this edit is done on remote repo not in local dir")
print("this edit is also done on remote rep not in local dir 2nd time")
print("this i done by directly commiting and not sending it to staging phase")
print("Adding new feature")
print("Changes made locally")
print("Adding feature Number 2")
print("another stash added")